application: mlog
version: 1
runtime: python
api_version: 1

handlers:
-   url: /rpc
    script: metaweblog.py

-   url: /rpc/.*
    script: metaweblog.py

-   url: /themes/[\w\-]+/templates/.*
    script: blog.py

-   url: /themes
    static_dir: themes

-   url: /.*
    script: blog.py
